#ifndef QOBJECTBROWSER_GLOBAL_H
#define QOBJECTBROWSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QOBJECTBROWSER_LIBRARY)
    #define QOBJECTBROWSERSHARED_EXPORT Q_DECL_EXPORT
#else
    #define QOBJECTBROWSERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif  /* QOBJECTBROWSER_GLOBAL_H */
